from __future__ import annotations

from appv22.extensions.base import ObservationContract, SkillCard

FILE_MANAGEMENT_SKILL = SkillCard(
    skill_id="file_management.model_authored_files",
    extension_id="file_management",
    triggers=(
        "workspace",
        "record",
        "leave",
        "useful",
        "next person",
        "capture",
        "decision",
        "durable file",
        "file",
        "files",
        "path",
        "paths",
        "folder",
        "folders",
        "dir",
        "directory",
        "directories",
        "ls",
        "list",
        "read",
        "open",
        "show",
        "print",
        "display",
        "content",
        "contents",
        ".txt",
        ".md",
        ".json",
        "write",
        "checklist",
        "note",
        "notes",
        "onboarding",
        "runbook",
        "stub",
        "create",
        "document",
        "handoff",
    ),
    modes=("START", "THINK", "OBSERVE", "ACT", "VERIFY"),
    summary="Pi-style file workspace tools: list workspace contents, read exact file content, and write or move files through explicit tool calls.",
    always_active=False,
    tool_ids=(
        "file_management.repo_snapshot",
        "file_management.read_file",
        "file_management.write_file",
        "file_management.mkdir",
        "file_management.move_file",
        "file_management.copy_file",
        "file_management.delete_file",
    ),
    instructions=(
        "Use file_management.repo_snapshot like Pi's ls/find surface: list files/directories and lightweight previews before choosing exact reads.",
        "Use file_management.read_file like Pi's read tool: read exact file content instead of guessing from summaries when the answer depends on content.",
        "Use file_management.write_file like Pi's write tool: write complete file content to the requested path; create parent directories as needed.",
        "Use mkdir, move_file, copy_file, and delete_file only when the user asks for filesystem changes.",
        "For multi-step file requests, continue using selected tools until each clear requested file operation is backed by tool evidence before finalizing.",
        "Do not invent manifests, moves, deletes, or records unless the latest user request asks for them.",
        "If persisted world_refs contain usable payload for the exact requested evidence, answer from that evidence instead of replaying broad observation.",
        "If persisted evidence is only a pointer without usable payload and exact facts are required, rehydrate with the selected observe tool.",
        "Reason internally; all workspace reads and mutations happen through explicit selected tool calls.",
    ),
    observation_contract=ObservationContract(
        evidence_kinds=("file_management.repo_snapshot",),
        preferred_tool_id="file_management.repo_snapshot",
    ),
)
