"""Terminal rendering, components, input, and interactive interfaces."""

from travis.tui.components import (
    Box,
    CancellableLoader,
    CombinedAutocompleteProvider,
    Component,
    Container,
    CURSOR_MARKER,
    Editor,
    FooterComponent,
    Image,
    Input,
    Loader,
    Markdown,
    SelectItem,
    SelectList,
    SettingsList,
    SimpleAutocompleteProvider,
    Spacer,
    StatusLine,
    Text,
    TruncatedText,
    format_cwd_for_footer,
)
from travis.tui.fuzzy import (
    FuzzyMatch,
    fuzzy_filter,
    fuzzy_match,
)
from travis.tui.builtin_themes import BUILTIN_THEMES, resolve_builtin_theme
from travis.tui.interactive import (
    AssistantMessageComponent,
    BashExecutionComponent,
    BranchSummaryMessageComponent,
    CompactionSummaryMessageComponent,
    CustomMessageComponent,
    InteractiveRenderer,
    ParsedSkillBlock,
    SkillInvocationMessageComponent,
    ToolExecutionComponent,
    UserMessageComponent,
    message_to_component,
    parse_skill_block,
    user_message_to_component,
)
from travis.tui.interactive_mode import InteractiveMode
from travis.tui.keybindings import (
    KeybindingsManager,
    TUI_KEYBINDINGS,
    get_keybindings,
    set_keybindings,
)
from travis.tui.keys import (
    Key,
    decode_kitty_printable,
    is_key_release,
    is_key_repeat,
    is_kitty_protocol_active,
    matches_key,
    parse_key,
    set_kitty_protocol_active,
)
from travis.tui.kill_ring import KillRing
from travis.tui.motion import MotionController, MotionSnapshot, MotionState
from travis.tui.native_modifiers import is_native_modifier_pressed
from travis.tui.stdin_buffer import StdinBuffer
from travis.tui.terminal import FakeTerminal, ProcessTerminal, Terminal
from travis.tui.terminal_colors import (
    is_osc11_background_color_response,
    parse_osc11_background_color,
)
from travis.tui.terminal_image import (
    CellDimensions,
    ImageCellSize,
    ImageDimensions,
    ImageProtocol,
    TerminalCapabilities,
    allocate_image_id,
    calculate_image_cell_size,
    calculate_image_rows,
    delete_all_kitty_images,
    delete_kitty_image,
    detect_capabilities,
    encode_iterm2,
    encode_kitty,
    get_capabilities,
    get_cell_dimensions,
    get_gif_dimensions,
    get_image_dimensions,
    get_jpeg_dimensions,
    get_png_dimensions,
    get_webp_dimensions,
    hyperlink,
    image_fallback,
    is_image_line,
    render_image,
    reset_capabilities_cache,
    set_capabilities,
    set_cell_dimensions,
)
from travis.tui.theme import (
    REQUIRED_THEME_ROLES,
    ResolvedTheme,
    ThemeContext,
    ThemeDiagnostic,
    resolve_theme,
)
from travis.tui.theme_controller import ThemeController
from travis.tui.tui import (
    RenderInfo,
    TUI,
    is_focusable,
)
from travis.tui.undo_stack import UndoStack
from travis.tui.utils import (
    extract_segments,
    slice_by_column,
    slice_with_width,
    strip_ansi,
    truncate_to_width,
    visible_width,
    wrap_text,
)
from travis.tui.word_navigation import (
    WordSegment,
    find_word_backward,
    find_word_forward,
)

__all__ = [
    "AssistantMessageComponent",
    "BashExecutionComponent",
    "BUILTIN_THEMES",
    "Box",
    "BranchSummaryMessageComponent",
    "CancellableLoader",
    "CombinedAutocompleteProvider",
    "CompactionSummaryMessageComponent",
    "CURSOR_MARKER",
    "Component",
    "Container",
    "CustomMessageComponent",
    "Editor",
    "FakeTerminal",
    "FooterComponent",
    "format_cwd_for_footer",
    "FuzzyMatch",
    "Image",
    "ImageCellSize",
    "ImageDimensions",
    "ImageProtocol",
    "fuzzy_filter",
    "fuzzy_match",
    "find_word_backward",
    "find_word_forward",
    "Input",
    "InteractiveMode",
    "InteractiveRenderer",
    "Key",
    "KeybindingsManager",
    "KillRing",
    "Loader",
    "Markdown",
    "MotionController",
    "MotionSnapshot",
    "MotionState",
    "ParsedSkillBlock",
    "ProcessTerminal",
    "RenderInfo",
    "REQUIRED_THEME_ROLES",
    "ResolvedTheme",
    "SelectItem",
    "SelectList",
    "SettingsList",
    "SimpleAutocompleteProvider",
    "Spacer",
    "StatusLine",
    "StdinBuffer",
    "SkillInvocationMessageComponent",
    "TUI",
    "TUI_KEYBINDINGS",
    "Terminal",
    "TerminalCapabilities",
    "ThemeContext",
    "ThemeController",
    "ThemeDiagnostic",
    "Text",
    "ToolExecutionComponent",
    "TruncatedText",
    "UndoStack",
    "UserMessageComponent",
    "WordSegment",
    "allocate_image_id",
    "calculate_image_cell_size",
    "calculate_image_rows",
    "delete_all_kitty_images",
    "delete_kitty_image",
    "detect_capabilities",
    "decode_kitty_printable",
    "encode_iterm2",
    "encode_kitty",
    "extract_segments",
    "is_key_release",
    "is_key_repeat",
    "is_kitty_protocol_active",
    "is_osc11_background_color_response",
    "is_native_modifier_pressed",
    "get_keybindings",
    "get_capabilities",
    "get_cell_dimensions",
    "get_gif_dimensions",
    "get_image_dimensions",
    "get_jpeg_dimensions",
    "get_png_dimensions",
    "get_webp_dimensions",
    "hyperlink",
    "image_fallback",
    "is_focusable",
    "matches_key",
    "message_to_component",
    "parse_osc11_background_color",
    "parse_skill_block",
    "parse_key",
    "render_image",
    "reset_capabilities_cache",
    "resolve_builtin_theme",
    "resolve_theme",
    "set_capabilities",
    "set_cell_dimensions",
    "set_keybindings",
    "set_kitty_protocol_active",
    "slice_by_column",
    "slice_with_width",
    "strip_ansi",
    "truncate_to_width",
    "user_message_to_component",
    "visible_width",
    "wrap_text",
]
