"""Original built-in Travis234 semantic palettes."""

from __future__ import annotations

from types import MappingProxyType
from typing import Mapping

from travis.tui.theme import ResolvedTheme, ThemeDiagnostic, resolve_theme


def _semantic_colors() -> dict[str, object]:
    return {
        "accent": "accent",
        "border": "border",
        "borderAccent": "accent_alt",
        "borderMuted": "border_muted",
        "success": "success",
        "error": "error",
        "warning": "warning",
        "muted": "muted",
        "dim": "dim",
        "text": "text",
        "thinkingText": "thinking_text",
        "selectedBg": "selected_bg",
        "userMessageBg": "user_bg",
        "userMessageText": "user_text",
        "customMessageBg": "custom_bg",
        "customMessageText": "custom_text",
        "customMessageLabel": "accent_alt",
        "toolPendingBg": "tool_pending_bg",
        "toolSuccessBg": "tool_success_bg",
        "toolErrorBg": "tool_error_bg",
        "toolTitle": "accent_alt",
        "toolOutput": "text",
        "mdHeading": "accent",
        "mdLink": "link",
        "mdLinkUrl": "muted",
        "mdCode": "code",
        "mdCodeBlock": "code",
        "mdCodeBlockBorder": "border_muted",
        "mdQuote": "thinking_text",
        "mdQuoteBorder": "accent_alt",
        "mdHr": "border_muted",
        "mdListBullet": "accent",
        "toolDiffAdded": "diff_added",
        "toolDiffRemoved": "diff_removed",
        "toolDiffContext": "diff_context",
        "syntaxComment": "syntax_comment",
        "syntaxKeyword": "syntax_keyword",
        "syntaxFunction": "syntax_function",
        "syntaxVariable": "syntax_variable",
        "syntaxString": "syntax_string",
        "syntaxNumber": "syntax_number",
        "syntaxType": "syntax_type",
        "syntaxOperator": "syntax_operator",
        "syntaxPunctuation": "syntax_punctuation",
        "thinkingOff": "thinking_off",
        "thinkingMinimal": "thinking_minimal",
        "thinkingLow": "thinking_low",
        "thinkingMedium": "thinking_medium",
        "thinkingHigh": "thinking_high",
        "thinkingXhigh": "thinking_xhigh",
        "bashMode": "bash",
    }


def _definition(variables: Mapping[str, object]) -> Mapping[str, object]:
    return MappingProxyType(
        {
            "vars": MappingProxyType(dict(variables)),
            "colors": MappingProxyType(_semantic_colors()),
        }
    )


BUILTIN_THEMES: Mapping[str, Mapping[str, object]] = MappingProxyType(
    {
        "Signal Glass": _definition(
            {
                "accent": "#00f0bd",
                "accent_alt": "#56d8ff",
                "border": "#268d7b",
                "border_muted": "#234b47",
                "success": "#4dff9f",
                "error": "#ff4d6d",
                "warning": "#ffc857",
                "muted": "#789b96",
                "dim": "#4c6965",
                "text": "#d8fff5",
                "thinking_text": "#8ebbb3",
                "selected_bg": "#164a43",
                "user_bg": "#0d302c",
                "user_text": "#e8fff9",
                "custom_bg": "#102f3a",
                "custom_text": "#dff8ff",
                "tool_pending_bg": "#2d2816",
                "tool_success_bg": "#123a2b",
                "tool_error_bg": "#401a24",
                "link": "#64e8ff",
                "code": "#b9ffe8",
                "diff_added": "#69ffa8",
                "diff_removed": "#ff6f8a",
                "diff_context": "#9cb8b3",
                "syntax_comment": "#668b84",
                "syntax_keyword": "#55e8ff",
                "syntax_function": "#42f5b3",
                "syntax_variable": "#d8fff5",
                "syntax_string": "#b8f56a",
                "syntax_number": "#ffc857",
                "syntax_type": "#8aa8ff",
                "syntax_operator": "#ff87dc",
                "syntax_punctuation": "#a6d1ca",
                "thinking_off": "#405a56",
                "thinking_minimal": "#47776e",
                "thinking_low": "#3c9985",
                "thinking_medium": "#20b994",
                "thinking_high": "#00d9aa",
                "thinking_xhigh": "#56d8ff",
                "bash": "#ffc857",
            }
        ),
        "Black Ice": _definition(
            {
                "accent": "#29d6ff",
                "accent_alt": "#8d7dff",
                "border": "#24557a",
                "border_muted": "#193249",
                "success": "#4ee6a8",
                "error": "#ff5577",
                "warning": "#f0b35a",
                "muted": "#7891a8",
                "dim": "#4b6479",
                "text": "#e6f7ff",
                "thinking_text": "#8faabd",
                "selected_bg": "#193e61",
                "user_bg": "#0b2942",
                "user_text": "#f1fbff",
                "custom_bg": "#211f47",
                "custom_text": "#eeeaff",
                "tool_pending_bg": "#312b1b",
                "tool_success_bg": "#11382f",
                "tool_error_bg": "#3b1826",
                "link": "#66e2ff",
                "code": "#bcdfff",
                "diff_added": "#5ce5a0",
                "diff_removed": "#ff6885",
                "diff_context": "#91a9ba",
                "syntax_comment": "#607a91",
                "syntax_keyword": "#8d7dff",
                "syntax_function": "#29d6ff",
                "syntax_variable": "#e6f7ff",
                "syntax_string": "#83e6c2",
                "syntax_number": "#f0b35a",
                "syntax_type": "#6ea8ff",
                "syntax_operator": "#d088ff",
                "syntax_punctuation": "#aac4d6",
                "thinking_off": "#40576a",
                "thinking_minimal": "#3c6885",
                "thinking_low": "#327da3",
                "thinking_medium": "#298fbd",
                "thinking_high": "#29b4df",
                "thinking_xhigh": "#8d7dff",
                "bash": "#66e2ff",
            }
        ),
        "Neon Oni": _definition(
            {
                "accent": "#ff2bd6",
                "accent_alt": "#37e7ff",
                "border": "#7c2fc4",
                "border_muted": "#3d245c",
                "success": "#43f5a7",
                "error": "#ff355e",
                "warning": "#ff9f43",
                "muted": "#9a7cab",
                "dim": "#674f73",
                "text": "#ffeaff",
                "thinking_text": "#b997c3",
                "selected_bg": "#4a176b",
                "user_bg": "#35113f",
                "user_text": "#fff0fc",
                "custom_bg": "#102f42",
                "custom_text": "#e5fbff",
                "tool_pending_bg": "#432617",
                "tool_success_bg": "#123b30",
                "tool_error_bg": "#4a1325",
                "link": "#37e7ff",
                "code": "#ffb5ed",
                "diff_added": "#50f0a5",
                "diff_removed": "#ff426c",
                "diff_context": "#bd9fc4",
                "syntax_comment": "#80648b",
                "syntax_keyword": "#b54cff",
                "syntax_function": "#37e7ff",
                "syntax_variable": "#ffeaff",
                "syntax_string": "#76f7bc",
                "syntax_number": "#ff9f43",
                "syntax_type": "#ff65dc",
                "syntax_operator": "#45d8ff",
                "syntax_punctuation": "#d2b7d8",
                "thinking_off": "#5a4263",
                "thinking_minimal": "#743d84",
                "thinking_low": "#9138a7",
                "thinking_medium": "#b332bd",
                "thinking_high": "#dc2bc9",
                "thinking_xhigh": "#37e7ff",
                "bash": "#ff9f43",
            }
        ),
        "Blood Circuit": _definition(
            {
                "accent": "#ff334f",
                "accent_alt": "#ff7a33",
                "border": "#9c2f3c",
                "border_muted": "#512b31",
                "success": "#54d98c",
                "error": "#ff2948",
                "warning": "#ff9d3d",
                "muted": "#a38a8e",
                "dim": "#6f585c",
                "text": "#f5e9e9",
                "thinking_text": "#b79a9f",
                "selected_bg": "#5b2029",
                "user_bg": "#3b181e",
                "user_text": "#fff2f2",
                "custom_bg": "#3b271b",
                "custom_text": "#fff0df",
                "tool_pending_bg": "#45311d",
                "tool_success_bg": "#17382a",
                "tool_error_bg": "#501721",
                "link": "#ff9a62",
                "code": "#ffd0bf",
                "diff_added": "#68dc96",
                "diff_removed": "#ff4962",
                "diff_context": "#b69fa2",
                "syntax_comment": "#806b6f",
                "syntax_keyword": "#ff4059",
                "syntax_function": "#ff7a33",
                "syntax_variable": "#f5e9e9",
                "syntax_string": "#d9b76c",
                "syntax_number": "#ff9d3d",
                "syntax_type": "#e46773",
                "syntax_operator": "#ff6d4d",
                "syntax_punctuation": "#cdb7b9",
                "thinking_off": "#60484c",
                "thinking_minimal": "#78464c",
                "thinking_low": "#984048",
                "thinking_medium": "#b73a45",
                "thinking_high": "#dc344a",
                "thinking_xhigh": "#ff7a33",
                "bash": "#ff9d3d",
            }
        ),
        "Reactor Gold": _definition(
            {
                "accent": "#ffd23f",
                "accent_alt": "#b7f34a",
                "border": "#8d772b",
                "border_muted": "#4b431f",
                "success": "#8ce04f",
                "error": "#ff5449",
                "warning": "#ffc43d",
                "muted": "#9b967c",
                "dim": "#68654f",
                "text": "#f6f0d6",
                "thinking_text": "#b4ae8e",
                "selected_bg": "#4d4419",
                "user_bg": "#332e16",
                "user_text": "#fff8dc",
                "custom_bg": "#26351a",
                "custom_text": "#efffda",
                "tool_pending_bg": "#483917",
                "tool_success_bg": "#24391a",
                "tool_error_bg": "#461d1c",
                "link": "#d9f75e",
                "code": "#ffe78f",
                "diff_added": "#9be35a",
                "diff_removed": "#ff645a",
                "diff_context": "#b4ae91",
                "syntax_comment": "#77745e",
                "syntax_keyword": "#ffd23f",
                "syntax_function": "#b7f34a",
                "syntax_variable": "#f6f0d6",
                "syntax_string": "#d7e86b",
                "syntax_number": "#ffae42",
                "syntax_type": "#e6cd64",
                "syntax_operator": "#ff8b45",
                "syntax_punctuation": "#c9c3a5",
                "thinking_off": "#5d5945",
                "thinking_minimal": "#6d6b3d",
                "thinking_low": "#7e822f",
                "thinking_medium": "#909d27",
                "thinking_high": "#a8bb2f",
                "thinking_xhigh": "#d7de37",
                "bash": "#b7f34a",
            }
        ),
        "Polar Ghost": _definition(
            {
                "accent": "#005bd8",
                "accent_alt": "#008cad",
                "border": "#7195b8",
                "border_muted": "#b4c6d6",
                "success": "#087f5b",
                "error": "#c92a45",
                "warning": "#9a6700",
                "muted": "#607487",
                "dim": "#8797a5",
                "text": "#172331",
                "thinking_text": "#526b7e",
                "selected_bg": "#c9e4ff",
                "user_bg": "#dceeff",
                "user_text": "#10263d",
                "custom_bg": "#d9f3f5",
                "custom_text": "#163a43",
                "tool_pending_bg": "#fff0c2",
                "tool_success_bg": "#d9f2e6",
                "tool_error_bg": "#ffe0e5",
                "link": "#006fa6",
                "code": "#334e68",
                "diff_added": "#087f5b",
                "diff_removed": "#c92a45",
                "diff_context": "#526b7e",
                "syntax_comment": "#718392",
                "syntax_keyword": "#5f3dc4",
                "syntax_function": "#005bd8",
                "syntax_variable": "#172331",
                "syntax_string": "#087f5b",
                "syntax_number": "#9a6700",
                "syntax_type": "#006fa6",
                "syntax_operator": "#a61e4d",
                "syntax_punctuation": "#4b6173",
                "thinking_off": "#a3b2bf",
                "thinking_minimal": "#839bad",
                "thinking_low": "#6688a1",
                "thinking_medium": "#467995",
                "thinking_high": "#216d91",
                "thinking_xhigh": "#005bd8",
                "bash": "#7a5200",
            }
        ),
    }
)


def resolve_builtin_theme(
    name: str = "Signal Glass",
    *,
    color_mode: str = "truecolor",
) -> tuple[ResolvedTheme, tuple[ThemeDiagnostic, ...]]:
    try:
        definition = BUILTIN_THEMES[name]
    except KeyError as error:
        raise ValueError(f"Unknown built-in theme: {name}") from error
    colors = definition["colors"]
    variables = definition["vars"]
    assert isinstance(colors, Mapping)
    assert isinstance(variables, Mapping)
    return resolve_theme(name, colors, variables, color_mode=color_mode, fallback=None)


__all__ = ["BUILTIN_THEMES", "resolve_builtin_theme"]
